services:
  cups:
    build:
      context: /home/mark/Works/NAS/docker/cups-avahi-airprint-master
      dockerfile: Dockerfile
    container_name: cups
    network_mode: host
    privileged: true
    devices:
      - /dev/usb/lp0:/dev/usb/lp0
      - /dev/bus/usb:/dev/bus/usb
    volumes:
       - /volume1/docker/cups_print_server/services:/services
       - /volume1/docker/cups_print_server/config:/config
    environment:
      CUPSADMIN: "cups"
      CUPSPASSWORD: "cups"
    restart: unless-stopped
